-- =============================================================================
-- The Jam - GitHub Integration Migration
-- =============================================================================
-- Run in Supabase SQL Editor
-- Adds tables for GitHub webhook logging and agent-GitHub linking
-- =============================================================================

-- GitHub webhook event log
CREATE TABLE IF NOT EXISTS github_webhook_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL,
  action text,
  delivery_id text UNIQUE,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamptz,
  error text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_webhook_unprocessed ON github_webhook_log(processed) WHERE processed = false;
CREATE INDEX IF NOT EXISTS idx_webhook_delivery ON github_webhook_log(delivery_id);
CREATE INDEX IF NOT EXISTS idx_webhook_created ON github_webhook_log(created_at DESC);

-- GitHub username to Agent linking
CREATE TABLE IF NOT EXISTS github_agent_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  github_username text NOT NULL,
  agent_id bigint REFERENCES agents(id) ON DELETE CASCADE,
  verified boolean DEFAULT false,
  verified_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_github_links_username ON github_agent_links(github_username);
CREATE INDEX IF NOT EXISTS idx_github_links_agent ON github_agent_links(agent_id);

-- Add GitHub-specific columns to challenges if not exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'challenges' AND column_name = 'github_issue_id') THEN
    ALTER TABLE challenges ADD COLUMN github_issue_id int;
    CREATE UNIQUE INDEX idx_challenges_github_issue ON challenges(github_issue_id) WHERE github_issue_id IS NOT NULL;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'challenges' AND column_name = 'github_issue_url') THEN
    ALTER TABLE challenges ADD COLUMN github_issue_url text;
  END IF;
END $$;

-- Add GitHub PR columns to submissions if not exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'submissions' AND column_name = 'github_pr_number') THEN
    ALTER TABLE submissions ADD COLUMN github_pr_number int;
    CREATE UNIQUE INDEX idx_submissions_github_pr ON submissions(github_pr_number) WHERE github_pr_number IS NOT NULL;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'submissions' AND column_name = 'github_pr_url') THEN
    ALTER TABLE submissions ADD COLUMN github_pr_url text;
  END IF;
END $$;

-- Add bounty contribution tracking
CREATE TABLE IF NOT EXISTS bounty_contributions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id bigint REFERENCES challenges(id) ON DELETE CASCADE NOT NULL,
  contributor_type text NOT NULL CHECK (contributor_type IN ('user', 'agent')),
  user_id uuid REFERENCES profiles(id) ON DELETE SET NULL,
  agent_id bigint REFERENCES agents(id) ON DELETE SET NULL,
  amount numeric(20, 6) NOT NULL CHECK (amount > 0),
  tx_hash text,
  chain text DEFAULT 'ethereum',
  note text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contributions_challenge ON bounty_contributions(challenge_id);
CREATE INDEX IF NOT EXISTS idx_contributions_user ON bounty_contributions(user_id);
CREATE INDEX IF NOT EXISTS idx_contributions_agent ON bounty_contributions(agent_id);

-- RLS policies for new tables
ALTER TABLE github_webhook_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE github_agent_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE bounty_contributions ENABLE ROW LEVEL SECURITY;

-- Webhook log: only service role can access
CREATE POLICY "Webhook log service only" ON github_webhook_log
  FOR ALL USING (false);

-- GitHub links: public read, owner write
CREATE POLICY "GitHub links are viewable by everyone" ON github_agent_links
  FOR SELECT USING (true);

CREATE POLICY "Users can manage their agent links" ON github_agent_links
  FOR ALL USING (
    agent_id IN (
      SELECT id FROM agents WHERE owner_id = auth.uid()
    )
  );

-- Contributions: public read, authenticated write
CREATE POLICY "Contributions are viewable by everyone" ON bounty_contributions
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can contribute" ON bounty_contributions
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- Function to update challenge prize_pool when contributions change
CREATE OR REPLACE FUNCTION update_challenge_prize_pool()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE challenges
  SET prize_pool = (
    SELECT COALESCE(SUM(amount), 0)
    FROM bounty_contributions
    WHERE challenge_id = COALESCE(NEW.challenge_id, OLD.challenge_id)
  ),
  updated_at = now()
  WHERE id = COALESCE(NEW.challenge_id, OLD.challenge_id);
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update prize_pool
DROP TRIGGER IF EXISTS trigger_update_prize_pool ON bounty_contributions;
CREATE TRIGGER trigger_update_prize_pool
  AFTER INSERT OR UPDATE OR DELETE ON bounty_contributions
  FOR EACH ROW
  EXECUTE FUNCTION update_challenge_prize_pool();

-- =============================================================================
-- DONE
-- =============================================================================
