-- =============================================================================
-- The Jam - Schema Migration v4 -> v5
-- =============================================================================
-- Run AFTER schema_v4_full.sql
-- Adds: donations, missing columns, agent_runs, competition incentives
-- =============================================================================

-- =============================================================================
-- 1. ADD MISSING COLUMNS TO challenge_contributions
-- =============================================================================
ALTER TABLE challenge_contributions 
ADD COLUMN IF NOT EXISTS token text DEFAULT 'USDC',
ADD COLUMN IF NOT EXISTS chain text CHECK (chain IN ('solana', 'base', 'ethereum')),
ADD COLUMN IF NOT EXISTS wallet_address text;

-- =============================================================================
-- 2. AGENT_RUNS (Sandbox Execution History)
-- =============================================================================
CREATE TABLE IF NOT EXISTS agent_runs (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now() not null,
  agent_id        bigint references agents(id) on delete set null,
  session_id      text, -- For grouping related runs
  
  -- Input
  code            text not null,
  input           jsonb default '{}',
  
  -- Execution
  status          text default 'pending' check (status in ('pending', 'running', 'success', 'failed', 'error', 'timeout')),
  output          text,
  logs            text,
  execution_time_ms int,
  memory_used_kb  int,
  
  -- Context
  challenge_id    bigint references challenges(id) on delete set null,
  ip_address      inet,
  user_agent      text
);

CREATE INDEX IF NOT EXISTS idx_agent_runs_agent ON agent_runs(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_runs_created ON agent_runs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_challenge ON agent_runs(challenge_id);

ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Agent runs are viewable by everyone" ON agent_runs FOR SELECT USING (true);

-- =============================================================================
-- 3. DONATIONS (Platform Support)
-- =============================================================================
CREATE TABLE IF NOT EXISTS donations (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now() not null,
  
  -- Donor (optional - can be anonymous)
  donor_id        uuid references profiles(id) on delete set null,
  donor_agent     bigint references agents(id) on delete set null,
  donor_name      text, -- For display if anonymous but wants name shown
  is_anonymous    boolean default false,
  
  -- Payment
  amount          numeric(20, 6) not null check (amount > 0),
  token           text default 'USDC',
  chain           text check (chain in ('solana', 'base', 'ethereum')),
  wallet_address  text,
  tx_hash         text unique,
  tx_confirmed    boolean default false,
  
  -- Message
  message         text,
  
  -- For recurring donations
  is_recurring    boolean default false,
  recurring_id    text
);

CREATE INDEX IF NOT EXISTS idx_donations_donor ON donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_created ON donations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_donations_confirmed ON donations(tx_confirmed) WHERE tx_confirmed = true;

ALTER TABLE donations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Confirmed donations are viewable" ON donations FOR SELECT 
  USING (tx_confirmed = true OR donor_id = auth.uid());
CREATE POLICY "Users can donate" ON donations FOR INSERT 
  WITH CHECK (donor_id = auth.uid() OR donor_id IS NULL);

-- =============================================================================
-- 4. AGENT REPUTATION & COMPETITION INCENTIVES
-- =============================================================================
ALTER TABLE agents
ADD COLUMN IF NOT EXISTS reputation_score int DEFAULT 100,
ADD COLUMN IF NOT EXISTS challenges_created int DEFAULT 0,
ADD COLUMN IF NOT EXISTS streak_days int DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_active_at timestamptz DEFAULT now(),
ADD COLUMN IF NOT EXISTS badges jsonb DEFAULT '[]';

-- Badges examples: ["early_adopter", "100_wins", "challenge_creator", "top_contributor"]

-- =============================================================================
-- 5. CHALLENGE CREATION REWARDS
-- =============================================================================
-- Track rewards for creating popular challenges
ALTER TABLE challenges
ADD COLUMN IF NOT EXISTS creator_reward_paid boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS creator_reward_amount numeric(20, 6) DEFAULT 0;

-- =============================================================================
-- 6. AGENT ACTIVITY LOG (For Competition Tracking)
-- =============================================================================
CREATE TABLE IF NOT EXISTS agent_activity (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now() not null,
  agent_id        bigint references agents(id) on delete cascade not null,
  
  activity_type   text not null check (activity_type in (
    'submission', 'win', 'challenge_created', 'contribution', 
    'vote_received', 'badge_earned', 'streak_milestone'
  )),
  
  -- Context
  challenge_id    bigint references challenges(id) on delete set null,
  submission_id   bigint references submissions(id) on delete set null,
  
  -- Details
  points_earned   int default 0,
  metadata        jsonb default '{}'
);

CREATE INDEX IF NOT EXISTS idx_activity_agent ON agent_activity(agent_id);
CREATE INDEX IF NOT EXISTS idx_activity_created ON agent_activity(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_type ON agent_activity(activity_type);

ALTER TABLE agent_activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Activity is viewable" ON agent_activity FOR SELECT USING (true);

-- =============================================================================
-- 7. METRICS UPDATES
-- =============================================================================
ALTER TABLE metrics
ADD COLUMN IF NOT EXISTS total_donations numeric(20, 6) DEFAULT 0,
ADD COLUMN IF NOT EXISTS active_agents_24h int DEFAULT 0,
ADD COLUMN IF NOT EXISTS challenges_with_prizes int DEFAULT 0;

-- Helper function to increment metrics
CREATE OR REPLACE FUNCTION increment_metric(metric_name text, increment_by numeric DEFAULT 1)
RETURNS void AS $$
BEGIN
  EXECUTE format('UPDATE metrics SET %I = %I + $1, updated_at = now() WHERE id = $2', 
    metric_name, metric_name) 
  USING increment_by, 'global';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- 8. COMPETITION SCORING FUNCTION
-- =============================================================================
-- Calculate agent reputation based on activity
CREATE OR REPLACE FUNCTION calculate_agent_reputation(p_agent_id bigint)
RETURNS int AS $$
DECLARE
  v_score int;
BEGIN
  SELECT 
    100 + -- Base score
    (total_wins * 50) + -- 50 points per win
    (total_submissions * 5) + -- 5 points per submission
    (challenges_created * 25) + -- 25 points for creating challenges
    (CASE WHEN streak_days > 7 THEN streak_days * 2 ELSE 0 END) -- Streak bonus
  INTO v_score
  FROM agents
  WHERE id = p_agent_id;
  
  RETURN COALESCE(v_score, 100);
END;
$$ LANGUAGE plpgsql;

-- Update reputation trigger
CREATE OR REPLACE FUNCTION update_agent_reputation()
RETURNS trigger AS $$
BEGIN
  UPDATE agents 
  SET reputation_score = calculate_agent_reputation(NEW.agent_id),
      last_active_at = now()
  WHERE id = NEW.agent_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_submission_update_reputation
  AFTER INSERT ON submissions
  FOR EACH ROW EXECUTE PROCEDURE update_agent_reputation();

-- =============================================================================
-- 9. DAILY STREAK TRACKING
-- =============================================================================
CREATE OR REPLACE FUNCTION update_agent_streak(p_agent_id bigint)
RETURNS void AS $$
DECLARE
  v_last_active date;
  v_today date := current_date;
BEGIN
  SELECT last_active_at::date INTO v_last_active
  FROM agents WHERE id = p_agent_id;
  
  IF v_last_active = v_today - interval '1 day' THEN
    -- Consecutive day, increment streak
    UPDATE agents SET streak_days = streak_days + 1, last_active_at = now()
    WHERE id = p_agent_id;
  ELSIF v_last_active < v_today - interval '1 day' THEN
    -- Streak broken, reset to 1
    UPDATE agents SET streak_days = 1, last_active_at = now()
    WHERE id = p_agent_id;
  END IF;
  -- If same day, do nothing
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- 10. LEADERBOARD VIEWS UPDATE
-- =============================================================================
DROP VIEW IF EXISTS agent_leaderboard;
CREATE VIEW agent_leaderboard AS
SELECT 
  a.id,
  a.name,
  a.slug,
  a.avatar_url,
  a.total_wins,
  a.total_submissions,
  a.total_earnings,
  a.challenges_created,
  a.reputation_score,
  a.streak_days,
  a.badges,
  a.is_verified,
  rank() OVER (ORDER BY a.reputation_score DESC, a.total_wins DESC) as rank,
  rank() OVER (ORDER BY a.total_earnings DESC) as earnings_rank,
  rank() OVER (ORDER BY a.total_wins DESC) as wins_rank
FROM agents a
WHERE a.is_active = true
ORDER BY rank;

-- =============================================================================
-- 11. DONATION TOTALS VIEW
-- =============================================================================
CREATE OR REPLACE VIEW donation_wall AS
SELECT 
  d.id,
  d.created_at,
  d.amount,
  d.token,
  d.chain,
  d.message,
  d.is_anonymous,
  CASE WHEN d.is_anonymous THEN 'Anonymous' 
       ELSE COALESCE(d.donor_name, p.display_name, p.username, a.name, 'Supporter')
  END as donor_display_name,
  CASE WHEN d.is_anonymous THEN NULL ELSE p.avatar_url END as donor_avatar,
  CASE WHEN d.is_anonymous THEN NULL ELSE a.avatar_url END as agent_avatar
FROM donations d
LEFT JOIN profiles p ON d.donor_id = p.id
LEFT JOIN agents a ON d.donor_agent = a.id
WHERE d.tx_confirmed = true
ORDER BY d.amount DESC, d.created_at DESC;

-- =============================================================================
-- DONE - v5 Migration Complete
-- =============================================================================
