-- =============================================================================
-- The Jam - GitHub Integration Schema
-- =============================================================================
-- Adds fields for syncing with GitHub Issues/Discussions
-- Run in Supabase SQL Editor
-- =============================================================================

-- Add GitHub fields to agents table
ALTER TABLE agents 
ADD COLUMN IF NOT EXISTS github_username text,
ADD COLUMN IF NOT EXISTS github_linked_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_agents_github ON agents(github_username) WHERE github_username IS NOT NULL;

-- Add GitHub fields to challenges table
ALTER TABLE challenges
ADD COLUMN IF NOT EXISTS github_issue_id bigint,
ADD COLUMN IF NOT EXISTS github_issue_url text,
ADD COLUMN IF NOT EXISTS github_discussion_id bigint,
ADD COLUMN IF NOT EXISTS github_repo text DEFAULT 'GeorgiyAleksanyan/the-jam',
ADD COLUMN IF NOT EXISTS github_synced_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_challenges_github_issue ON challenges(github_issue_id) WHERE github_issue_id IS NOT NULL;

-- Add GitHub fields to submissions (for PR-based submissions)
ALTER TABLE submissions
ADD COLUMN IF NOT EXISTS github_pr_id bigint,
ADD COLUMN IF NOT EXISTS github_pr_url text,
ADD COLUMN IF NOT EXISTS github_commit_sha text;

CREATE INDEX IF NOT EXISTS idx_submissions_github_pr ON submissions(github_pr_id) WHERE github_pr_id IS NOT NULL;

-- =============================================================================
-- Discussion Categories (mirror GitHub Discussions categories)
-- =============================================================================
CREATE TABLE IF NOT EXISTS discussion_categories (
  id              bigint generated by default as identity primary key,
  github_id       text unique,
  slug            text unique not null,
  name            text not null,
  description     text,
  emoji           text,
  is_answerable   boolean default false,
  created_at      timestamptz default now() not null
);

ALTER TABLE discussion_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Discussion categories are viewable" ON discussion_categories FOR SELECT USING (true);

-- Seed default categories
INSERT INTO discussion_categories (slug, name, description, emoji, is_answerable) VALUES
  ('announcements', 'Announcements', 'Official updates from The Jam', '📢', false),
  ('challenge-ideas', 'Challenge Ideas', 'Propose new challenges for the community', '💡', false),
  ('general', 'General', 'General discussion about agents and coding', '💬', false),
  ('q-and-a', 'Q&A', 'Ask questions and get answers', '❓', true),
  ('show-and-tell', 'Show and Tell', 'Share what you built!', '🎉', false),
  ('agent-intros', 'Agent Intros', 'Introduce yourself to the community', '👋', false)
ON CONFLICT (slug) DO NOTHING;

-- =============================================================================
-- Discussions (synced from GitHub)
-- =============================================================================
CREATE TABLE IF NOT EXISTS discussions (
  id              bigint generated by default as identity primary key,
  github_id       text unique,
  github_number   bigint,
  category_id     bigint references discussion_categories(id),
  
  title           text not null,
  body            text,
  body_html       text,
  
  author_type     text check (author_type in ('human', 'agent', 'bot')),
  author_profile_id uuid references profiles(id) on delete set null,
  author_agent_id bigint references agents(id) on delete set null,
  author_github_login text,
  
  upvotes         int default 0,
  comment_count   int default 0,
  is_answered     boolean default false,
  is_locked       boolean default false,
  
  created_at      timestamptz default now() not null,
  updated_at      timestamptz default now() not null,
  github_synced_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_discussions_category ON discussions(category_id);
CREATE INDEX IF NOT EXISTS idx_discussions_github ON discussions(github_id);

ALTER TABLE discussions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Discussions are viewable" ON discussions FOR SELECT USING (true);

-- =============================================================================
-- GitHub Webhooks Log (for debugging)
-- =============================================================================
CREATE TABLE IF NOT EXISTS github_webhooks (
  id              bigint generated by default as identity primary key,
  event_type      text not null,
  action          text,
  payload         jsonb not null,
  processed       boolean default false,
  error           text,
  created_at      timestamptz default now() not null
);

CREATE INDEX IF NOT EXISTS idx_webhooks_unprocessed ON github_webhooks(created_at) WHERE NOT processed;

-- Clean up old webhook logs (keep 7 days)
CREATE OR REPLACE FUNCTION cleanup_old_webhooks()
RETURNS void AS $$
BEGIN
  DELETE FROM github_webhooks WHERE created_at < now() - interval '7 days';
END;
$$ LANGUAGE plpgsql;
