-- =============================================================================
-- The Jam - Multi-Repo Challenge Sync Migration
-- =============================================================================
-- Adds support for syncing challenges from multiple GitHub repositories
-- Run in Supabase SQL Editor
-- =============================================================================

-- =============================================================================
-- 1. SOURCE REPOS - Track which repos feed challenges
-- =============================================================================
CREATE TABLE IF NOT EXISTS source_repos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner           text NOT NULL,
  name            text NOT NULL,
  full_name       text GENERATED ALWAYS AS (owner || '/' || name) STORED,
  display_name    text,
  description     text,
  challenge_label text DEFAULT 'jam-challenge',  -- Issues with this label become challenges
  is_active       boolean DEFAULT true,
  webhook_secret  text,  -- For verifying webhooks from this repo
  last_synced_at  timestamptz,
  created_at      timestamptz DEFAULT now(),
  
  UNIQUE(owner, name)
);

CREATE INDEX IF NOT EXISTS idx_source_repos_active ON source_repos(is_active) WHERE is_active = true;

ALTER TABLE source_repos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Source repos are viewable" ON source_repos FOR SELECT USING (true);

-- Seed initial repos
INSERT INTO source_repos (owner, name, display_name, description) VALUES
  ('GeorgiyAleksanyan', 'the-jam', 'The Jam', 'The Jam platform repository'),
  ('openclaw', 'openclaw', 'OpenClaw', 'OpenClaw main repository')
ON CONFLICT (owner, name) DO NOTHING;

-- =============================================================================
-- 2. UPDATE CHALLENGES - Add multi-repo and lifecycle fields
-- =============================================================================

-- Add source repo reference
ALTER TABLE challenges 
ADD COLUMN IF NOT EXISTS source_repo_id bigint REFERENCES source_repos(id),
ADD COLUMN IF NOT EXISTS github_issue_number bigint,
ADD COLUMN IF NOT EXISTS github_issue_state text CHECK (github_issue_state IN ('open', 'closed')),
ADD COLUMN IF NOT EXISTS github_labels jsonb DEFAULT '[]';

-- Add funding and voting thresholds
ALTER TABLE challenges
ADD COLUMN IF NOT EXISTS funding_threshold numeric(20, 6) DEFAULT 0,
ADD COLUMN IF NOT EXISTS voting_threshold int DEFAULT 3,
ADD COLUMN IF NOT EXISTS voting_start_at timestamptz,
ADD COLUMN IF NOT EXISTS voting_end_at timestamptz;

-- Update status check constraint to include new statuses
-- First drop existing constraint
ALTER TABLE challenges DROP CONSTRAINT IF EXISTS challenges_status_check;

-- Add new constraint with full lifecycle
ALTER TABLE challenges ADD CONSTRAINT challenges_status_check 
  CHECK (status IN (
    'proposed',      -- Synced from GitHub, not yet funded
    'funding',       -- Accepting funding contributions
    'open',          -- Funded, accepting submissions
    'active',        -- Has submissions, still accepting more
    'voting',        -- Submission period closed, voting open
    'judging',       -- Votes tallied, selecting winner
    'solved',        -- Winner selected and paid
    'closed',        -- Closed without winner
    'cancelled',     -- Cancelled by creator
    'draft'          -- Draft (legacy)
  ));

-- Create index for GitHub sync lookups
CREATE INDEX IF NOT EXISTS idx_challenges_github_sync 
  ON challenges(source_repo_id, github_issue_number) 
  WHERE github_issue_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_challenges_source_repo ON challenges(source_repo_id);

-- =============================================================================
-- 3. UPDATE SUBMISSIONS - Better PR tracking
-- =============================================================================

ALTER TABLE submissions
ADD COLUMN IF NOT EXISTS github_pr_number bigint,
ADD COLUMN IF NOT EXISTS github_pr_state text CHECK (github_pr_state IN ('open', 'closed', 'merged')),
ADD COLUMN IF NOT EXISTS github_pr_merged_at timestamptz,
ADD COLUMN IF NOT EXISTS github_ci_status text CHECK (github_ci_status IN ('pending', 'success', 'failure', 'error'));

CREATE INDEX IF NOT EXISTS idx_submissions_pr_number ON submissions(github_pr_number) WHERE github_pr_number IS NOT NULL;

-- =============================================================================
-- 4. CHALLENGE STATUS TRANSITIONS LOG
-- =============================================================================
CREATE TABLE IF NOT EXISTS challenge_status_log (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id    bigint REFERENCES challenges(id) ON DELETE CASCADE NOT NULL,
  from_status     text,
  to_status       text NOT NULL,
  reason          text,
  triggered_by    text CHECK (triggered_by IN ('system', 'webhook', 'cron', 'manual')),
  metadata        jsonb DEFAULT '{}',
  created_at      timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_status_log_challenge ON challenge_status_log(challenge_id);

ALTER TABLE challenge_status_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Status log is viewable" ON challenge_status_log FOR SELECT USING (true);

-- =============================================================================
-- 5. FUNCTION: Check and transition challenge status
-- =============================================================================
CREATE OR REPLACE FUNCTION check_challenge_status_transition(p_challenge_id bigint)
RETURNS text AS $$
DECLARE
  v_challenge RECORD;
  v_new_status text;
  v_submission_count int;
BEGIN
  SELECT * INTO v_challenge FROM challenges WHERE id = p_challenge_id;
  
  IF NOT FOUND THEN
    RETURN 'not_found';
  END IF;
  
  v_new_status := v_challenge.status;
  
  -- Count submissions
  SELECT COUNT(*) INTO v_submission_count FROM submissions WHERE challenge_id = p_challenge_id;
  
  -- Proposed -> Funding: when any funding added
  IF v_challenge.status = 'proposed' AND v_challenge.prize_pool > 0 THEN
    v_new_status := 'funding';
  END IF;
  
  -- Funding -> Open: when funding threshold met
  IF v_challenge.status IN ('proposed', 'funding') 
     AND v_challenge.prize_pool >= v_challenge.funding_threshold 
     AND v_challenge.funding_threshold > 0 THEN
    v_new_status := 'open';
  END IF;
  
  -- Open -> Active: when first submission received
  IF v_challenge.status = 'open' AND v_submission_count > 0 THEN
    v_new_status := 'active';
  END IF;
  
  -- Active -> Voting: when ends_at passed
  IF v_challenge.status = 'active' 
     AND v_challenge.ends_at IS NOT NULL 
     AND v_challenge.ends_at < now() THEN
    v_new_status := 'voting';
  END IF;
  
  -- Update if changed
  IF v_new_status != v_challenge.status THEN
    UPDATE challenges SET status = v_new_status, updated_at = now() WHERE id = p_challenge_id;
    
    INSERT INTO challenge_status_log (challenge_id, from_status, to_status, triggered_by)
    VALUES (p_challenge_id, v_challenge.status, v_new_status, 'system');
  END IF;
  
  RETURN v_new_status;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 6. TRIGGER: Auto-check status on prize_pool or submission changes
-- =============================================================================
CREATE OR REPLACE FUNCTION trigger_check_challenge_status()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_TABLE_NAME = 'challenges' THEN
    PERFORM check_challenge_status_transition(NEW.id);
  ELSIF TG_TABLE_NAME = 'submissions' THEN
    PERFORM check_challenge_status_transition(NEW.challenge_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS check_challenge_status_on_update ON challenges;
CREATE TRIGGER check_challenge_status_on_update
  AFTER UPDATE OF prize_pool ON challenges
  FOR EACH ROW
  EXECUTE FUNCTION trigger_check_challenge_status();

DROP TRIGGER IF EXISTS check_challenge_status_on_submission ON submissions;
CREATE TRIGGER check_challenge_status_on_submission
  AFTER INSERT ON submissions
  FOR EACH ROW
  EXECUTE FUNCTION trigger_check_challenge_status();

-- =============================================================================
-- DONE
-- =============================================================================
SELECT 'Multi-repo migration complete!' as status;
