-- Schema V3: Secure Agent Ecosystem
-- Run this in Supabase SQL Editor. It handles RLS and Security.

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles (Humans/Builders)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Profiles
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- 2. Challenges (The Arena Tasks)
create table if not exists challenges (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text unique not null, -- e.g., 'json-flattener'
  description text not null,
  difficulty text default 'easy', 
  input_schema jsonb, 
  output_schema jsonb,
  reward_pool numeric default 0,
  is_active boolean default true
);

-- Enable RLS for Challenges
alter table challenges enable row level security;
create policy "Challenges are viewable by everyone" on challenges for select using (true);
-- Only service role (admin) can insert/update challenges for now

-- 3. Agents (Registered Bots)
create table if not exists agents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  owner_id uuid references profiles(id) default auth.uid(),
  name text not null,
  description text,
  repo_url text, -- Github link
  api_key_hash text, -- For agent authentication
  is_verified boolean default false
);

-- Enable RLS for Agents
alter table agents enable row level security;
create policy "Agents are viewable by everyone" on agents for select using (true);
create policy "Users can insert own agents" on agents for insert with check (auth.uid() = owner_id);
create policy "Users can update own agents" on agents for update using (auth.uid() = owner_id);

-- 4. Submissions (Attempts)
create table if not exists submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  agent_id bigint references agents(id),
  challenge_id bigint references challenges(id),
  code text, 
  status text default 'pending', -- pending, success, failed, error
  logs text,
  output text,
  execution_time_ms integer,
  is_public boolean default true
);

-- Enable RLS for Submissions
alter table submissions enable row level security;
create policy "Public submissions are viewable" on submissions for select using (is_public = true);
create policy "Agents/Owners can submit" on submissions for insert with check (
  exists (select 1 from agents where id = submissions.agent_id and owner_id = auth.uid())
);

-- 5. Tools (The Standard Library)
-- Winning submissions become tools
create table if not exists tools (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text unique not null,
  description text,
  submission_id bigint references submissions(id),
  usage_count bigint default 0
);

alter table tools enable row level security;
create policy "Tools are viewable by everyone" on tools for select using (true);

-- Seed Data: Challenge
insert into challenges (title, slug, description, difficulty, input_schema, output_schema)
values (
  'The Flattener',
  'flattener',
  'Flatten a nested JSON object into dot-notation keys.',
  'easy',
  '{"type": "object"}',
  '{"type": "object", "description": "Flat key-value pairs"}'
) on conflict (slug) do nothing;
