-- =============================================================================
-- The Jam - Full Platform Schema v4
-- =============================================================================
-- Run in Supabase SQL Editor
-- This is the complete schema for the full platform build
-- =============================================================================

-- Enable extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- =============================================================================
-- 1. PROFILES (Human Users)
-- =============================================================================
create table if not exists profiles (
  id              uuid references auth.users on delete cascade primary key,
  username        text unique,
  display_name    text,
  avatar_url      text,
  bio             text,
  github_username text,
  wallet_address  text,
  wallet_chain    text check (wallet_chain in ('solana', 'base', 'ethereum')),
  created_at      timestamptz default now() not null,
  updated_at      timestamptz default now() not null
);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, display_name, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data->>'username',
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for auto-profile creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- RLS for profiles
alter table profiles enable row level security;
create policy "Profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- =============================================================================
-- 2. AGENTS (Bot Accounts)
-- =============================================================================
create table if not exists agents (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now() not null,
  updated_at      timestamptz default now() not null,
  owner_id        uuid references profiles(id) on delete cascade not null,
  name            text not null,
  slug            text unique not null,
  description     text,
  avatar_url      text,
  website_url     text,
  github_repo     text,
  api_key_hash    text not null,
  wallet_address  text,
  wallet_chain    text check (wallet_chain in ('solana', 'base', 'ethereum')),
  is_verified     boolean default false,
  is_active       boolean default true,
  total_wins      int default 0,
  total_submissions int default 0,
  total_earnings  numeric(20, 6) default 0,
  metadata        jsonb default '{}'
);

create index idx_agents_owner on agents(owner_id);
create index idx_agents_slug on agents(slug);
create index idx_agents_verified on agents(is_verified) where is_verified = true;

alter table agents enable row level security;
create policy "Agents are viewable by everyone" on agents for select using (true);
create policy "Users can insert own agents" on agents for insert with check (auth.uid() = owner_id);
create policy "Users can update own agents" on agents for update using (auth.uid() = owner_id);
create policy "Users can delete own agents" on agents for delete using (auth.uid() = owner_id);

-- =============================================================================
-- 3. TOPICS (Categories/Tags)
-- =============================================================================
create table if not exists topics (
  id              bigint generated by default as identity primary key,
  slug            text unique not null,
  name            text not null,
  description     text,
  color           text default '#6366f1',
  icon            text,
  challenge_count int default 0,
  created_at      timestamptz default now() not null
);

alter table topics enable row level security;
create policy "Topics are viewable by everyone" on topics for select using (true);

-- Seed default topics
insert into topics (slug, name, description, color, icon) values
  ('tooling', 'Tooling', 'Build tools, scripts, and utilities', '#10b981', '🔧'),
  ('data', 'Data Processing', 'Parse, transform, and analyze data', '#3b82f6', '📊'),
  ('creative', 'Creative', 'Art, writing, and design challenges', '#ec4899', '🎨'),
  ('algorithms', 'Algorithms', 'Classic CS problems and optimizations', '#f59e0b', '🧮'),
  ('web', 'Web Development', 'Frontend, backend, and full-stack', '#8b5cf6', '🌐'),
  ('ai', 'AI & ML', 'Machine learning and AI tasks', '#06b6d4', '🤖'),
  ('security', 'Security', 'CTF-style security challenges', '#ef4444', '🔒'),
  ('fun', 'Just for Fun', 'Silly, experimental, or absurd', '#84cc16', '🎮')
on conflict (slug) do nothing;

-- =============================================================================
-- 4. CHALLENGES (Competitions)
-- =============================================================================
create table if not exists challenges (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now() not null,
  updated_at      timestamptz default now() not null,
  
  -- Creator (human or agent)
  created_by      uuid references profiles(id) on delete set null,
  created_by_agent bigint references agents(id) on delete set null,
  
  -- Basic info
  slug            text unique not null,
  title           text not null,
  description     text not null,
  short_description text, -- For cards/previews
  
  -- Classification
  difficulty      text default 'easy' check (difficulty in ('easy', 'medium', 'hard', 'legendary')),
  status          text default 'draft' check (status in ('draft', 'open', 'active', 'voting', 'closed', 'cancelled')),
  
  -- Timing
  starts_at       timestamptz,
  ends_at         timestamptz,
  voting_ends_at  timestamptz,
  
  -- Rewards
  prize_pool      numeric(20, 6) default 0,
  prize_currency  text default 'USDC',
  entry_fee       numeric(20, 6) default 0,
  
  -- Limits
  max_submissions int,
  max_submissions_per_agent int default 3,
  
  -- Content
  default_code    text,
  default_input   jsonb default '{}',
  test_cases      jsonb default '[]',
  judging_criteria text,
  
  -- Stats
  upvotes         int default 0,
  view_count      int default 0,
  submission_count int default 0,
  
  -- Payout
  winner_agent_id bigint references agents(id),
  payout_tx       text,
  payout_at       timestamptz
);

create index idx_challenges_status on challenges(status);
create index idx_challenges_created_by on challenges(created_by);
create index idx_challenges_ends_at on challenges(ends_at);
create index idx_challenges_prize on challenges(prize_pool desc);

alter table challenges enable row level security;
create policy "Challenges are viewable by everyone" on challenges for select using (true);
create policy "Users can create challenges" on challenges for insert with check (auth.uid() = created_by);
create policy "Creators can update own challenges" on challenges for update 
  using (auth.uid() = created_by and status in ('draft', 'open'));

-- =============================================================================
-- 5. CHALLENGE_TOPICS (Many-to-Many)
-- =============================================================================
create table if not exists challenge_topics (
  challenge_id    bigint references challenges(id) on delete cascade,
  topic_id        bigint references topics(id) on delete cascade,
  primary key (challenge_id, topic_id)
);

alter table challenge_topics enable row level security;
create policy "Challenge topics are viewable" on challenge_topics for select using (true);

-- =============================================================================
-- 6. CHALLENGE_CONTRIBUTIONS (Prize Pool Funding)
-- =============================================================================
create table if not exists challenge_contributions (
  id              bigint generated by default as identity primary key,
  challenge_id    bigint references challenges(id) on delete cascade not null,
  contributor_id  uuid references profiles(id) on delete set null,
  contributor_agent bigint references agents(id) on delete set null,
  amount          numeric(20, 6) not null check (amount > 0),
  currency        text default 'USDC',
  tx_hash         text,
  tx_confirmed    boolean default false,
  created_at      timestamptz default now() not null,
  
  check (contributor_id is not null or contributor_agent is not null)
);

create index idx_contributions_challenge on challenge_contributions(challenge_id);

alter table challenge_contributions enable row level security;
create policy "Contributions are viewable" on challenge_contributions for select using (true);
create policy "Users can contribute" on challenge_contributions for insert 
  with check (auth.uid() = contributor_id);

-- Update prize pool on contribution
create or replace function update_challenge_prize_pool()
returns trigger as $$
begin
  update challenges 
  set prize_pool = prize_pool + new.amount,
      updated_at = now()
  where id = new.challenge_id;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_contribution_added
  after insert on challenge_contributions
  for each row execute procedure update_challenge_prize_pool();

-- =============================================================================
-- 7. SUBMISSIONS (Agent Solutions)
-- =============================================================================
create table if not exists submissions (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz default now() not null,
  updated_at      timestamptz default now() not null,
  
  challenge_id    bigint references challenges(id) on delete cascade not null,
  agent_id        bigint references agents(id) on delete cascade not null,
  
  -- Code
  code            text not null,
  input           jsonb default '{}',
  
  -- Execution
  status          text default 'pending' check (status in ('pending', 'running', 'success', 'failed', 'error', 'timeout', 'disqualified')),
  output          text,
  logs            text,
  execution_time_ms int,
  
  -- Scoring
  auto_score      int, -- From test cases
  vote_score      int default 0,
  final_score     int default 0,
  rank            int,
  
  -- Winner
  is_winner       boolean default false,
  payout_amount   numeric(20, 6),
  payout_tx       text,
  
  unique(challenge_id, agent_id, created_at) -- Allow multiple attempts
);

create index idx_submissions_challenge on submissions(challenge_id);
create index idx_submissions_agent on submissions(agent_id);
create index idx_submissions_status on submissions(status);
create index idx_submissions_winner on submissions(is_winner) where is_winner = true;

alter table submissions enable row level security;
create policy "Submissions are viewable" on submissions for select using (true);
-- Agents submit via API with service role

-- Update submission count
create or replace function update_challenge_submission_count()
returns trigger as $$
begin
  update challenges 
  set submission_count = submission_count + 1,
      updated_at = now()
  where id = new.challenge_id;
  
  update agents
  set total_submissions = total_submissions + 1,
      updated_at = now()
  where id = new.agent_id;
  
  return new;
end;
$$ language plpgsql security definer;

create trigger on_submission_added
  after insert on submissions
  for each row execute procedure update_challenge_submission_count();

-- =============================================================================
-- 8. VOTES (Human Judging)
-- =============================================================================
create table if not exists votes (
  id              bigint generated by default as identity primary key,
  submission_id   bigint references submissions(id) on delete cascade not null,
  voter_id        uuid references profiles(id) on delete cascade not null,
  weight          int default 1 check (weight >= 1 and weight <= 10),
  created_at      timestamptz default now() not null,
  
  unique(submission_id, voter_id)
);

create index idx_votes_submission on votes(submission_id);
create index idx_votes_voter on votes(voter_id);

alter table votes enable row level security;
create policy "Votes are viewable" on votes for select using (true);
create policy "Users can vote" on votes for insert with check (auth.uid() = voter_id);
create policy "Users can change vote" on votes for update using (auth.uid() = voter_id);
create policy "Users can remove vote" on votes for delete using (auth.uid() = voter_id);

-- Update vote score
create or replace function update_submission_vote_score()
returns trigger as $$
begin
  if TG_OP = 'DELETE' then
    update submissions 
    set vote_score = vote_score - old.weight,
        updated_at = now()
    where id = old.submission_id;
    return old;
  else
    update submissions 
    set vote_score = vote_score + new.weight,
        updated_at = now()
    where id = new.submission_id;
    return new;
  end if;
end;
$$ language plpgsql security definer;

create trigger on_vote_changed
  after insert or delete on votes
  for each row execute procedure update_submission_vote_score();

-- =============================================================================
-- 9. UPVOTES (Challenge Popularity)
-- =============================================================================
create table if not exists upvotes (
  id              bigint generated by default as identity primary key,
  challenge_id    bigint references challenges(id) on delete cascade not null,
  user_id         uuid references profiles(id) on delete cascade not null,
  created_at      timestamptz default now() not null,
  
  unique(challenge_id, user_id)
);

create index idx_upvotes_challenge on upvotes(challenge_id);

alter table upvotes enable row level security;
create policy "Upvotes are viewable" on upvotes for select using (true);
create policy "Users can upvote" on upvotes for insert with check (auth.uid() = user_id);
create policy "Users can remove upvote" on upvotes for delete using (auth.uid() = user_id);

-- Update upvote count
create or replace function update_challenge_upvotes()
returns trigger as $$
begin
  if TG_OP = 'DELETE' then
    update challenges set upvotes = upvotes - 1 where id = old.challenge_id;
    return old;
  else
    update challenges set upvotes = upvotes + 1 where id = new.challenge_id;
    return new;
  end if;
end;
$$ language plpgsql security definer;

create trigger on_upvote_changed
  after insert or delete on upvotes
  for each row execute procedure update_challenge_upvotes();

-- =============================================================================
-- 10. METRICS (Site-wide Stats - Cached)
-- =============================================================================
create table if not exists metrics (
  id              text primary key default 'global',
  site_visits     bigint default 0,
  agents_connected bigint default 0,
  humans_registered bigint default 0,
  challenges_created bigint default 0,
  submissions_total bigint default 0,
  total_prize_paid numeric(20, 6) default 0,
  updated_at      timestamptz default now() not null
);

-- Initialize global metrics
insert into metrics (id) values ('global') on conflict do nothing;

alter table metrics enable row level security;
create policy "Metrics are viewable" on metrics for select using (true);

-- =============================================================================
-- 11. AGENT_RUNS (Legacy - for sandbox testing)
-- =============================================================================
-- Keep agent_runs for the current Arena sandbox mode
-- This is for quick testing without challenge context

-- (Already created in schema_mvp.sql, keeping for compatibility)

-- =============================================================================
-- 12. API_KEYS (For Agent Authentication)
-- =============================================================================
create table if not exists api_keys (
  id              bigint generated by default as identity primary key,
  agent_id        bigint references agents(id) on delete cascade not null,
  key_prefix      text not null, -- First 8 chars for identification
  key_hash        text not null,
  name            text default 'Default',
  last_used_at    timestamptz,
  created_at      timestamptz default now() not null,
  expires_at      timestamptz,
  is_active       boolean default true
);

create index idx_api_keys_agent on api_keys(agent_id);
create index idx_api_keys_prefix on api_keys(key_prefix);

alter table api_keys enable row level security;
create policy "Users can view own agent keys" on api_keys for select 
  using (exists (select 1 from agents where agents.id = api_keys.agent_id and agents.owner_id = auth.uid()));
create policy "Users can manage own agent keys" on api_keys for all 
  using (exists (select 1 from agents where agents.id = api_keys.agent_id and agents.owner_id = auth.uid()));

-- =============================================================================
-- HELPER FUNCTIONS
-- =============================================================================

-- Generate URL-safe slug from title
create or replace function generate_slug(title text)
returns text as $$
begin
  return lower(regexp_replace(regexp_replace(title, '[^a-zA-Z0-9\s-]', '', 'g'), '\s+', '-', 'g'));
end;
$$ language plpgsql;

-- Generate API key (returns plain key, stores hash)
create or replace function generate_api_key(p_agent_id bigint, p_name text default 'Default')
returns text as $$
declare
  v_key text;
  v_prefix text;
  v_hash text;
begin
  -- Generate random key: jam_<32 random chars>
  v_key := 'jam_' || encode(gen_random_bytes(24), 'base64');
  v_key := replace(replace(v_key, '+', ''), '/', ''); -- URL safe
  v_prefix := substring(v_key from 1 for 12);
  v_hash := crypt(v_key, gen_salt('bf'));
  
  insert into api_keys (agent_id, key_prefix, key_hash, name)
  values (p_agent_id, v_prefix, v_hash, p_name);
  
  -- Also update the agent's api_key_hash for quick auth
  update agents set api_key_hash = v_hash where id = p_agent_id;
  
  return v_key; -- Return plain key (only time it's visible)
end;
$$ language plpgsql security definer;

-- =============================================================================
-- VIEWS
-- =============================================================================

-- Leaderboard view
create or replace view agent_leaderboard as
select 
  a.id,
  a.name,
  a.slug,
  a.avatar_url,
  a.total_wins,
  a.total_submissions,
  a.total_earnings,
  a.is_verified,
  coalesce(a.total_earnings, 0) as earnings_display,
  rank() over (order by a.total_wins desc, a.total_earnings desc) as rank
from agents a
where a.is_active = true
order by rank;

-- Active challenges view
create or replace view active_challenges as
select 
  c.*,
  p.username as creator_username,
  p.avatar_url as creator_avatar,
  a.name as creator_agent_name,
  a.slug as creator_agent_slug
from challenges c
left join profiles p on c.created_by = p.id
left join agents a on c.created_by_agent = a.id
where c.status in ('open', 'active', 'voting')
order by c.prize_pool desc, c.created_at desc;

-- =============================================================================
-- DONE
-- =============================================================================
