-- Schema MVP: Simple Agent Runs
-- This supports the current Arena flow: submit code -> run -> see results
-- Run this in Supabase SQL Editor.

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Agent Runs (Execution History)
-- This is the core table for the MVP Arena
create table if not exists agent_runs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Submission data
  code text not null,
  input jsonb default '{}',
  challenge_id text, -- Optional: links to a challenge slug
  
  -- Execution results
  status text default 'pending' check (status in ('pending', 'running', 'success', 'failed', 'error', 'timeout')),
  output text,
  logs text,
  execution_time_ms integer,
  
  -- Optional: user/session tracking (for future auth)
  session_id text, -- Anonymous session tracking
  user_id uuid references auth.users(id) on delete set null,
  
  -- Metadata
  ip_hash text, -- For rate limiting / abuse detection (hashed for privacy)
  user_agent text
);

-- Indexes for common queries
create index if not exists idx_agent_runs_created_at on agent_runs(created_at desc);
create index if not exists idx_agent_runs_status on agent_runs(status);
create index if not exists idx_agent_runs_challenge on agent_runs(challenge_id);

-- Enable RLS
alter table agent_runs enable row level security;

-- Policies
-- Anyone can view runs (public leaderboard style)
create policy "Agent runs are viewable by everyone" 
  on agent_runs for select 
  using (true);

-- Anyone can insert (anonymous submissions allowed for MVP)
create policy "Anyone can submit agent runs" 
  on agent_runs for insert 
  with check (true);

-- Only service role can update (API backend updates status/output)
-- This prevents clients from faking results
create policy "Only service role can update runs" 
  on agent_runs for update 
  using (false);

-- Challenges table (optional for MVP, but useful for structure)
create table if not exists challenges (
  id text primary key, -- Slug: 'flattener', 'sandbox'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  difficulty text default 'easy' check (difficulty in ('easy', 'medium', 'hard', 'legendary')),
  default_code text,
  default_input jsonb default '{}',
  test_cases jsonb default '[]', -- For automated validation
  is_active boolean default true
);

alter table challenges enable row level security;
create policy "Challenges are viewable by everyone" on challenges for select using (true);

-- Seed challenges
insert into challenges (id, title, description, difficulty, default_code, default_input) values
(
  'sandbox',
  'Sandbox (Playground)',
  'Free form testing. No rules.',
  'easy',
  E'// Write your agent code here\nfunction agent(input) {\n  return "Hello " + (input.data.name || "World");\n}',
  '{"name": "Ether"}'
),
(
  'flattener',
  'Challenge: The Flattener',
  'Flatten a nested JSON object into dot-notation keys.',
  'easy',
  E'function agent(input) {\n  const obj = input.data;\n  const result = {};\n  \n  // TODO: Implement recursion to flatten ''obj''\n  // Example: { a: { b: 1 } } -> { "a.b": 1 }\n  \n  return result;\n}',
  '{"user": {"name": "Sovereign", "stats": {"level": 99, "class": "Construct"}}, "active": true}'
)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  default_code = excluded.default_code,
  default_input = excluded.default_input;

-- Drop old 'agents' table if it exists and conflicts
-- WARNING: Only run this if you want to start fresh
-- drop table if exists agents cascade;
