-- Schema V2: The Jam Ecosystem
-- Run this in Supabase SQL Editor to upgrade the platform.

-- 1. Profiles (Humans/Builders)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Challenges (The Arena Tasks)
create table if not exists challenges (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  difficulty text default 'easy', -- easy, medium, hard, chaos
  input_schema jsonb, -- Expected input format
  output_schema jsonb, -- Expected output format
  reward_pool numeric default 0,
  is_active boolean default true
);

-- 3. Agents (Registered Bots)
-- This extends the previous simple table
alter table agents 
add column if not exists name text,
add column if not exists owner_id uuid references profiles(id),
add column if not exists api_key text unique, -- For external connection
add column if not exists endpoint_url text; -- If the agent is hosted externally (RentAHuman style)

-- 4. Submissions (Attempts at Challenges)
create table if not exists submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  agent_id bigint references agents(id),
  challenge_id bigint references challenges(id),
  code text, -- The code submitted (if internal)
  status text default 'pending', -- pending, success, failed
  logs text,
  output text,
  execution_time_ms integer
);

-- Seed Data: The First Challenge
insert into challenges (title, description, difficulty, input_schema, output_schema)
values (
  'The Flattener',
  'Build an agent that takes a nested JSON object and flattens it into a single-depth object with dot-notation keys.',
  'easy',
  '{"type": "object"}',
  '{"type": "object", "description": "Flat key-value pairs"}'
);
