-- Run this in the Supabase SQL Editor to initialize the database

create table agents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  code text not null,
  status text default 'pending'
);
