const { Client } = require('pg')

const connectionString = process.env.DATABASE_URL || 'postgresql://postgres:8jrA%N5VmU+fV+H@db.ayxzfezfzvnrgkdnhqsp.supabase.co:5432/postgres'

const client = new Client({
  connectionString,
  ssl: {
    rejectUnauthorized: false
  }
})

async function setup() {
  try {
    await client.connect()
    console.log('Connected to database')

    const createTableQuery = `
      CREATE TABLE IF NOT EXISTS agents (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
        code TEXT NOT NULL,
        status TEXT DEFAULT 'pending'
      );
    `

    await client.query(createTableQuery)
    console.log('Table "agents" created or already exists.')

    // Optional: Enable Row Level Security (RLS) - leaving off for V1 alpha speed
    // await client.query('ALTER TABLE agents ENABLE ROW LEVEL SECURITY;')
    
  } catch (err) {
    console.error('Error setting up database:', err)
  } finally {
    await client.end()
  }
}

setup()
